function  theta = F_onlineRL_all (GrO0, np, datIdx, a0a, r0r, X0, Y0, ...
    gamma, T, w_0, theta_0, md, zetaC, zetaA, OptAlg, valBnd, beta, nseRwd, nseSt, ...
    w_r, theta_r, nmethod )

if strcmpi( nmethod, 'noWS' )
    theta = F_onlineRL (GrO0, np, datIdx, 'gamma',gamma,'TT',T,'theta',[], ...
        'mydim',md,'zetaC',zetaC,'zetaA',zetaA,'OptAlg',OptAlg,'valBnd',valBnd, ...
        'beta',beta,'nseRwd',nseRwd,'nseSt',nseSt,'TT0',20);
elseif strcmpi( nmethod, 'WS' )
    theta = F_onlineRL_warmSt (GrO0, np, datIdx, a0a, r0r, X0, Y0, ...
        'gamma',gamma,'TT',T,'theta',theta_0,'w',w_0,'mydim',md,...
        'zetaC',zetaC,'zetaA',zetaA,'OptAlg',OptAlg,'valBnd',valBnd, ...
        'beta',beta,'nseRwd',nseRwd,'nseSt',nseSt,'TT0',1);
elseif strcmpi( nmethod, 'eachWS' )
    theta = F_onlineRL_warmSt (GrO0, np, datIdx, a0a, r0r, X0, Y0, ...
        'gamma',gamma,'TT',T,'theta',theta_r,'w',w_r,'mydim',md,...
        'zetaC',zetaC,'zetaA',zetaA,'OptAlg',OptAlg,'valBnd',valBnd, ...
        'beta',beta,'nseRwd',nseRwd,'nseSt',nseSt,'TT0',1);
end
end